---
abstract: 'We are Taiwanese CPAN Authors!'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Taiwanese
requires:
  Acme::CPANAuthors::Register: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gugod/acme-cpanauthors-taiwanese/issues
  repository: git://github.com/gugod/acme-cpanauthors-taiwanese.git
version: 0.08
